### PR TITLE
Added intersection observer for canvas

### PR DESCRIPTION
**Pull request by jannickbath**
## Feature
If the canvas isn't visible anymore, it hides itself. (display --> none)

### Why do i want to implement such feature?
I wanted to give you some inspiration on how you could implement a feature, that stops the animation if necessary. (Out of viewport).

## Note
**This code does <ins>not</ins> fix ( Issue #8 ), but it's a good starting point!**

### CODE REVIEW

**Comment by EdwardAbboud** [comment]
This is really cool! Have you tested it on your end? When implemented i monitored the container and it did not show any changes to 'display' on scroll

**Comment by jannickbath** [comment]
Yes i tested it. But the pull request is 4 days old, depending on your new CSS, it might not work.

**Comment by jannickbath** [comment]
Also, since you lowered the amount of particles in your animation the performance is decent for me.

**Comment by EdwardAbboud** [comment]
I tried implementing it, nothing has changed that would affect the code, especially javascript-wise. Yes i'm thinking of making it a video instead, low quality and loop it. Could be better for performance

**Comment by jannickbath** [comment]
Sounds like a good idea.

**Pull request closed without merging**
