### PR TITLE
Navbar fixes, minor CSS cleanup

### LINKED ISSUE #20: Navbar Issues
## Desktop-Navbar

1. Should be at the top of the page (just for smaller screens)
2. Should be sticky

## Mobile-Navbar
1. Should be hidden, if the desktop version of the page is viewed
2. Icon should be used as **toggle** not just for opening the burger-menu

### PR DESCRIPTION
**Pull request by jannickbath**
# Changes

## Navbar

- fixed #20 
- removed  unnecessary **javascript**

<br />

A *little bit* of CSS cleanup.

### CODE REVIEW

**Comment by EdwardAbboud** [comment]
Some of this looks good! I'm not too sure about the amount of data that was added though. Seems a little over-kill for this. Do you know of anyway to possibly increase efficiency with embedded media? Is it better by any chance to have a carousel kind of section for the video (where the user is able to click 'next' or 'back' to flip through the videos? or does that not change performance?

**Comment by jannickbath** [comment]
I get your point. I'm going to remove the documentation.

Adding a carousel for the media shouldn't affect the performance.
Maybe replacing the embeds with some kind of placeholder while they're still loading might do the trick. If they are fully loaded, they can be replaced by the actual content.

**Comment by jannickbath** [comment]
Alright, i removed the documentation.
@EdwardAbboud

**Comment by EdwardAbboud** [comment]
Amazing, perhaps i will try to split the sections into their own html pages (i.e. home, music, videos etc..) the user can then have the flexibility to load the page they're interested in without having too much visual stimulation. If it fixes the performance issue then perfect. Otherwise i'll also try the placeholder until the iframes are loaded. It's either that or having the actual media files uploaded, which might be troublesome for the user i think.

**Pull request merged**
